# Generated by Django 5.1.4 on 2024-12-05 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CateringOrChef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("personal_chef", "Personal Chef"),
                            ("catering", "Catering"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vegetarian_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("north_indian", "North Indian Vegetarian"),
                            ("south_indian", "South Indian Vegetarian"),
                            ("gujarati", "Gujarati Vegetarian"),
                            ("jain", "Jain Vegetarian"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "non_vegetarian_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("north_indian", "North Indian Non-Vegetarian"),
                            ("south_indian", "South Indian Non-Vegetarian"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dietary_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vegan", "Vegan"),
                            ("keto", "Keto"),
                            ("halal", "Halal"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "balinese_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jimbaran_seafood", "Jimbaran Seafood"),
                            ("balinese_culinary", "Balinese Culinary"),
                            ("indonesian_food", "Indonesian Food"),
                            ("local_snacks", "Local Snacks"),
                            ("souvenir_foods", "Souvenir Foods"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("other_preferences", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetable Vendor"),
                            ("utensil", "Utensil Vendor"),
                            ("travel_agent", "Travel Agent"),
                            ("event_organizer", "Event Organizer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contact_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JourneyPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("occupation", models.CharField(max_length=150)),
                ("times_visited_bali", models.IntegerField(default=0)),
                (
                    "crew_type",
                    models.CharField(
                        choices=[
                            ("business_partners", "Business Partners"),
                            ("corporate_meeting", "Corporate Meeting"),
                            ("team_bonding", "Team Bonding"),
                            ("alumni_meeting", "Alumni Meeting"),
                            ("friends_get_together", "Friends Get-Together"),
                            ("family", "Family"),
                            ("new_couple", "New Couple"),
                            ("family_get_together", "Family Get-Together"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "crew_type_others",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requests", models.TextField()),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperworkAssistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistance_type",
                    models.CharField(
                        choices=[
                            ("kyc_integration", "KYC Integration"),
                            ("visa_processing", "Visa Processing Assistance"),
                            ("travel_requirements", "Travel Requirement Guidance"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("other_assistance_details", models.TextField(blank=True, null=True)),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacesToVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("natural_beauty", "Natural Beauty and Beaches"),
                            ("local_culture", "Local Cultures and Traditions"),
                            ("wellness_relaxation", "Wellness and Relaxation"),
                            ("wedding_pre_wedding", "Wedding and Pre-Wedding"),
                            ("adventures_activities", "Adventures and Activities"),
                            ("local_culinary", "Local Culinary"),
                            ("shopping", "Shopping in Bali"),
                            ("luxury_experiences", "Luxury and Unique Experiences"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("others_description", models.TextField(blank=True, null=True)),
                (
                    "journey_preferences",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StayPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stay_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("motel", "Motel"),
                            ("villa", "Villa"),
                            ("cottage", "Cottage"),
                            ("apartment", "Apartment"),
                            ("guesthouse", "Guesthouse"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourGuidePreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("tamil", "Tamil"),
                            ("english", "English"),
                            ("hindi", "Hindi"),
                            ("marathi", "Marathi"),
                            ("gujarati", "Gujarati"),
                            ("kannada", "Kannada"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_language",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("international_airport", models.CharField(max_length=100)),
                ("flight_class", models.CharField(max_length=50)),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorbike", "Motorbike (1-2 people)"),
                            ("bus", "Bus (>30 people)"),
                            ("minibus", "MiniBus (20-30 people)"),
                            ("van", "Van (12-15 people)"),
                            ("car", "Car (5-10 people)"),
                            ("luxury_car", "Luxury Car (5-8 people)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rent_period",
                    models.CharField(
                        choices=[
                            ("1_2_days", "1-2 Days"),
                            ("more_than_3_days", ">3 Days"),
                        ],
                        max_length=20,
                    ),
                ),
                ("include_driver", models.BooleanField(default=False)),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
            ],
        ),
    ]
