# Generated by Django 5.1.4 on 2024-12-12 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traveldetails",
            old_name="departure_date",
            new_name="from_date",
        ),
        migrations.RenameField(
            model_name="traveldetails",
            old_name="arrival_date",
            new_name="to_date",
        ),
        migrations.RemoveField(
            model_name="traveldetails",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="traveldetails",
            name="departure_time",
        ),
    ]
