# Generated by Django 5.1.4 on 2024-12-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0003_alter_placestovisit_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staypreferences",
            name="stay_type",
            field=models.TextField(
                choices=[
                    ("hotel", "Hotel"),
                    ("motel", "Motel"),
                    ("villa", "Villa"),
                    ("cottage", "Cottage"),
                    ("apartment", "Apartment"),
                    ("guesthouse", "Guesthouse"),
                ],
                max_length=50,
            ),
        ),
    ]
