# Generated by Django 5.1.4 on 2024-12-13 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0004_alter_staypreferences_stay_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="name",
        ),
    ]
