# Generated by Django 5.1.4 on 2024-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0005_remove_vendor_contact_info_remove_vendor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.TextField(
                choices=[
                    ("vegetable", "Vegetable Vendor"),
                    ("utensil", "Utensil Vendor"),
                    ("travel_agent", "Travel Agent"),
                    ("event_organizer", "Event Organizer"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
