# Generated by Django 5.1.4 on 2024-12-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0008_alter_journeypreferences_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldetails",
            name="journey_preferences",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="journeys.journeypreferences",
            ),
        ),
    ]
