# Generated by Django 5.1.4 on 2024-12-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0009_alter_traveldetails_journey_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placestovisit",
            name="journey_preferences",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="journeys.journeypreferences",
            ),
        ),
        migrations.AlterField(
            model_name="traveldetails",
            name="journey_preferences",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="journeys.journeypreferences",
            ),
        ),
    ]
