# Generated by Django 5.1.4 on 2024-12-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0011_alter_placestovisit_journey_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staypreferences",
            name="stay_type",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("motel", "Motel"),
                    ("villa", "Villa"),
                    ("cottage", "Cottage"),
                    ("apartment", "Apartment"),
                    ("guesthouse", "Guesthouse"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("vegetable", "Vegetable Vendor"),
                    ("utensil", "Utensil Vendor"),
                    ("travel_agent", "Travel Agent"),
                    ("event_organizer", "Event Organizer"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
