# Generated by Django 5.1.4 on 2024-12-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0012_alter_staypreferences_stay_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cateringorchef",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("personal_chef", "Personal Chef"),
                    ("catering", "Catering"),
                    ("others", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("vegetable", "Vegetable Vendor"),
                    ("utensil", "Utensil Vendor"),
                    ("travel_agent", "Travel Agent"),
                    ("event_organizer", "Event Organizer"),
                    ("others", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
