# Generated by Django 5.1.4 on 2024-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0013_alter_cateringorchef_service_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placestovisit",
            name="place",
            field=models.CharField(
                choices=[
                    ("natural_beauty", "Natural Beauty and Beaches"),
                    ("local_culture", "Local Cultures and Traditions"),
                    ("wellness_relaxation", "Wellness and Relaxation"),
                    ("wedding_pre_wedding", "Wedding and Pre-Wedding"),
                    ("adventures_activities", "Adventures and Activities"),
                    ("local_culinary", "Local Culinary"),
                    ("shopping", "Shopping in Bali"),
                    ("luxury_experiences", "Luxury and Unique Experiences"),
                    ("others", "Others"),
                ]
            ),
        ),
    ]
