# Generated by Django 5.1.4 on 2024-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0015_alter_placestovisit_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("kyc_integration", "KYC Integration"),
                            ("visa_processing", "Visa Processing Assistance"),
                            ("travel_requirements", "Travel Requirement Guidance"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BalineseChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_name",
                    models.CharField(
                        choices=[
                            ("jimbaran_seafood", "Jimbaran Seafood"),
                            ("balinese_culinary", "Balinese Culinary"),
                            ("indonesian_food", "Indonesian Food"),
                            ("local_snacks", "Local Snacks"),
                            ("souvenir_foods", "Souvenir Foods"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietaryChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_name",
                    models.CharField(
                        choices=[
                            ("vegan", "Vegan"),
                            ("keto", "Keto"),
                            ("halal", "Halal"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_name",
                    models.CharField(
                        choices=[
                            ("tamil", "Tamil"),
                            ("english", "English"),
                            ("hindi", "Hindi"),
                            ("marathi", "Marathi"),
                            ("gujarati", "Gujarati"),
                            ("kannada", "Kannada"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonVegetarianChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_name",
                    models.CharField(
                        choices=[
                            ("north_indian", "North Indian Non-Vegetarian"),
                            ("south_indian", "South Indian Non-Vegetarian"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        choices=[
                            ("natural_beauty", "Natural Beauty and Beaches"),
                            ("local_culture", "Local Cultures and Traditions"),
                            ("wellness_relaxation", "Wellness and Relaxation"),
                            ("wedding_pre_wedding", "Wedding and Pre-Wedding"),
                            ("adventures_activities", "Adventures and Activities"),
                            ("local_culinary", "Local Culinary"),
                            ("shopping", "Shopping in Bali"),
                            ("luxury_experiences", "Luxury and Unique Experiences"),
                            ("others", "Others"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StayType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stay_type_name",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("motel", "Motel"),
                            ("villa", "Villa"),
                            ("cottage", "Cottage"),
                            ("apartment", "Apartment"),
                            ("guesthouse", "Guesthouse"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VegetarianChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_name",
                    models.CharField(
                        choices=[
                            ("north_indian", "North Indian Vegetarian"),
                            ("south_indian", "South Indian Vegetarian"),
                            ("gujarati", "Gujarati Vegetarian"),
                            ("jain", "Jain Vegetarian"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type_name",
                    models.CharField(
                        choices=[
                            ("motorbike", "Motorbike (1-2 people)"),
                            ("bus", "Bus (>30 people)"),
                            ("minibus", "MiniBus (20-30 people)"),
                            ("van", "Van (12-15 people)"),
                            ("car", "Car (5-10 people)"),
                            ("luxury_car", "Luxury Car (5-8 people)"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetable Vendor"),
                            ("utensil", "Utensil Vendor"),
                            ("travel_agent", "Travel Agent"),
                            ("event_organizer", "Event Organizer"),
                            ("others", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="foodpreferences",
            name="balinese_choice",
        ),
        migrations.RemoveField(
            model_name="foodpreferences",
            name="dietary_choice",
        ),
        migrations.RemoveField(
            model_name="foodpreferences",
            name="non_vegetarian_choice",
        ),
        migrations.RemoveField(
            model_name="foodpreferences",
            name="vegetarian_choice",
        ),
        migrations.RemoveField(
            model_name="placestovisit",
            name="place",
        ),
        migrations.RemoveField(
            model_name="tourguidepreferences",
            name="preferred_language",
        ),
        migrations.AddField(
            model_name="vehiclepreferences",
            name="other_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="paperworkassistance",
            name="assistance_type",
        ),
        migrations.RemoveField(
            model_name="staypreferences",
            name="stay_type",
        ),
        migrations.RemoveField(
            model_name="vehiclepreferences",
            name="vehicle_type",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="vendor_type",
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="balinese_choices",
            field=models.ManyToManyField(to="journeys.balinesechoice"),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="dietary_choices",
            field=models.ManyToManyField(to="journeys.dietarychoice"),
        ),
        migrations.AddField(
            model_name="tourguidepreferences",
            name="preferred_languages",
            field=models.ManyToManyField(to="journeys.language"),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="non_vegetarian_choices",
            field=models.ManyToManyField(to="journeys.nonvegetarianchoice"),
        ),
        migrations.AddField(
            model_name="placestovisit",
            name="places",
            field=models.ManyToManyField(to="journeys.place"),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="vegetarian_choices",
            field=models.ManyToManyField(to="journeys.vegetarianchoice"),
        ),
        migrations.AddField(
            model_name="paperworkassistance",
            name="assistance_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="paperwork_assistances",
                to="journeys.assistancetype",
            ),
        ),
        migrations.AddField(
            model_name="staypreferences",
            name="stay_type",
            field=models.ManyToManyField(to="journeys.staytype"),
        ),
        migrations.AddField(
            model_name="vehiclepreferences",
            name="vehicle_type",
            field=models.ManyToManyField(to="journeys.vehicletype"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_type",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="journeys.vendortype"
            ),
        ),
    ]
