# Generated by Django 5.1.4 on 2024-12-17 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "journeys",
            "0016_assistancetype_balinesechoice_dietarychoice_language_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodpreferences",
            old_name="balinese_choices",
            new_name="balinese_choice",
        ),
        migrations.RenameField(
            model_name="foodpreferences",
            old_name="dietary_choices",
            new_name="dietary_choice",
        ),
        migrations.RenameField(
            model_name="foodpreferences",
            old_name="non_vegetarian_choices",
            new_name="non_vegetarian_choice",
        ),
        migrations.RenameField(
            model_name="foodpreferences",
            old_name="vegetarian_choices",
            new_name="vegetarian_choice",
        ),
    ]
