# Generated by Django 5.1.4 on 2024-12-18 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "journeys",
            "0017_rename_balinese_choices_foodpreferences_balinese_choice_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="placestovisit",
            old_name="places",
            new_name="place",
        ),
    ]
