# Generated by Django 5.1.4 on 2024-12-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0019_remove_placestovisit_place_delete_place_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        choices=[
                            ("natural_beauty", "Natural Beauty and Beaches"),
                            ("local_culture", "Local Cultures and Traditions"),
                            ("wellness_relaxation", "Wellness and Relaxation"),
                            ("wedding_pre_wedding", "Wedding and Pre-Wedding"),
                            ("adventures_activities", "Adventures and Activities"),
                            ("local_culinary", "Local Culinary"),
                            ("shopping", "Shopping in Bali"),
                            ("luxury_experiences", "Luxury and Unique Experiences"),
                            ("others", "Others"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="placestovisit",
            name="place",
        ),
        migrations.AddField(
            model_name="placestovisit",
            name="place",
            field=models.ManyToManyField(to="journeys.place"),
        ),
    ]
