# Generated by Django 5.1.4 on 2024-12-27 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0020_place_remove_placestovisit_place_placestovisit_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placestovisit",
            name="place",
        ),
    ]
