# Generated by Django 5.1.4 on 2024-12-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0023_alter_place_place_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staytype",
            name="stay_type_name",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("motel", "Motel"),
                    ("villa", "Villa"),
                    ("cottage", "Cottage"),
                    ("apartment", "Apartment"),
                    ("guesthouse", "Guesthouse"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
