# Generated by Django 5.1.4 on 2024-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0025_alter_balinesechoice_choice_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiclepreferences",
            old_name="vehicle_type",
            new_name="vehicle",
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="vehicle_type_name",
            field=models.CharField(
                choices=[
                    ("motorbike", "Motorbike (1-2 people)"),
                    ("bus", "Bus (>30 people)"),
                    ("minibus", "MiniBus (20-30 people)"),
                    ("van", "Van (12-15 people)"),
                    ("car", "Car (5-10 people)"),
                    ("luxury_car", "Luxury Car (5-8 people)"),
                    ("others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
