# Generated by Django 5.1.4 on 2024-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0027_alter_vehiclepreferences_include_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language_name",
            field=models.CharField(
                choices=[
                    ("tamil", "Tamil"),
                    ("english", "English"),
                    ("hindi", "Hindi"),
                    ("marathi", "Marathi"),
                    ("gujarati", "Gujarati"),
                    ("kannada", "Kannada"),
                    ("others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepreferences",
            name="rent_period",
            field=models.CharField(
                choices=[
                    ("1_2_days", "1-2 Days"),
                    ("more_than_3_days", ">3 Days"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
