# Generated by Django 5.1.4 on 2024-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0028_alter_language_language_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistancetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("kyc_integration", "KYC Integration"),
                    ("visa_processing", "Visa Processing Assistance"),
                    ("travel_requirements", "Travel Requirement Guidance"),
                    ("others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paperworkassistance",
            name="assistance_type",
            field=models.ManyToManyField(blank=True, to="journeys.assistancetype"),
        ),
    ]
