# Generated by Django 5.1.4 on 2024-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0029_alter_assistancetype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendortype",
            name="name",
            field=models.CharField(
                choices=[
                    ("vegetable", "Vegetable Vendor"),
                    ("utensil", "Utensil Vendor"),
                    ("travel_agent", "Travel Agent"),
                    ("event_organizer", "Event Organizer"),
                    ("others", "Other"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
