# Generated by Django 5.1.4 on 2025-01-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0030_alter_vendortype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balinesechoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("jimbaran_seafood", "Jimbaran Seafood"),
                    ("balinese_culinary", "Balinese Culinary"),
                    ("indonesian_food", "Indonesian Food"),
                    ("local_snacks", "Local Snacks"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="dietarychoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("vegan", "Vegan"),
                    ("keto", "Keto"),
                    ("halal", "Halal"),
                    ("souvenir_foods", "Souvenir Foods"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
