# Generated by Django 5.1.4 on 2025-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0031_alter_balinesechoice_choice_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldetails",
            name="international_airport",
            field=models.CharField(
                choices=[
                    (
                        "indira_gandhi_international",
                        "Indira Gandhi International Airport (Delhi)",
                    ),
                    (
                        "chhatrapati_shivaji_maharaj_international",
                        "Chhatrapati Shivaji Maharaj International Airport (Mumbai)",
                    ),
                    (
                        "kempegowda_international",
                        "Kempegowda International Airport (Bangalore)",
                    ),
                    (
                        "netaji_subhas_chandra_bose_international",
                        "Netaji Subhas Chandra Bose International Airport (Kolkata)",
                    ),
                    (
                        "chennai_international",
                        "Chennai International Airport (Chennai)",
                    ),
                    (
                        "rajiv_gandhi_international",
                        "Rajiv Gandhi International Airport (Hyderabad)",
                    ),
                    (
                        "sardar_vallabhbhai_patel_international",
                        "Sardar Vallabhbhai Patel International Airport (Ahmedabad)",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
