# Generated by Django 5.1.4 on 2025-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0033_journeypreferences_number_of_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="journeypreferences",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
