# Generated by Django 5.1.4 on 2025-02-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journeys", "0034_journeypreferences_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistancetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("KYC Integration", "KYC Integration"),
                    ("Visa Processing Assistance", "Visa Processing Assistance"),
                    ("Travel Requirement Guidance", "Travel Requirement Guidance"),
                    ("Others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="balinesechoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("Jimbaran Seafood", "Jimbaran Seafood"),
                    ("Balinese Culinary", "Balinese Culinary"),
                    ("Indonesian Food", "Indonesian Food"),
                    ("Local Snacks", "Local Snacks"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cateringorchef",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Personal Chef", "Personal Chef"),
                    ("Catering", "Catering"),
                    ("others", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dietarychoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("Vegan", "Vegan"),
                    ("Keto", "Keto"),
                    ("Halal", "Halal"),
                    ("Souvenir Foods", "Souvenir Foods"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language_name",
            field=models.CharField(
                choices=[
                    ("Tamil", "Tamil"),
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                    ("Marathi", "Marathi"),
                    ("Gujarati", "Gujarati"),
                    ("Kannada", "Kannada"),
                    ("Others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="nonvegetarianchoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("North Indian Non-Vegetarian", "North Indian Non-Vegetarian"),
                    ("South Indian Non-Vegetarian", "South Indian Non-Vegetarian"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_name",
            field=models.CharField(
                choices=[
                    ("Natural Beauty and Beaches", "Natural Beauty and Beaches"),
                    ("Local Cultures and Traditions", "Local Cultures and Traditions"),
                    ("Wellness and Relaxation", "Wellness and Relaxation"),
                    ("Wedding and Pre-Wedding", "Wedding and Pre-Wedding"),
                    ("Adventures and Activities", "Adventures and Activities"),
                    ("Local Culinary", "Local Culinary"),
                    ("Shopping in Bali", "Shopping in Bali"),
                    ("Luxury and Unique Experiences", "Luxury and Unique Experiences"),
                    ("Others", "Others"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staytype",
            name="stay_type_name",
            field=models.CharField(
                choices=[
                    ("Hotel", "Hotel"),
                    ("Motel", "Motel"),
                    ("Villa", "Villa"),
                    ("Cottage", "Cottage"),
                    ("Apartment", "Apartment"),
                    ("Guesthouse", "Guesthouse"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="traveldetails",
            name="international_airport",
            field=models.CharField(
                choices=[
                    (
                        "Indira Gandhi International Airport (Delhi)",
                        "Indira Gandhi International Airport (Delhi)",
                    ),
                    (
                        "Chhatrapati Shivaji Maharaj International Airport (Mumbai)",
                        "Chhatrapati Shivaji Maharaj International Airport (Mumbai)",
                    ),
                    (
                        "Kempegowda International Airport (Bangalore)",
                        "Kempegowda International Airport (Bangalore)",
                    ),
                    (
                        "Netaji Subhas Chandra Bose International Airport (Kolkata)",
                        "Netaji Subhas Chandra Bose International Airport (Kolkata)",
                    ),
                    (
                        "Chennai International Airport (Chennai)",
                        "Chennai International Airport (Chennai)",
                    ),
                    (
                        "Rajiv Gandhi International Airport (Hyderabad)",
                        "Rajiv Gandhi International Airport (Hyderabad)",
                    ),
                    (
                        "Sardar Vallabhbhai Patel International Airport (Ahmedabad)",
                        "Sardar Vallabhbhai Patel International Airport (Ahmedabad)",
                    ),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vegetarianchoice",
            name="choice_name",
            field=models.CharField(
                choices=[
                    ("North Indian Vegetarian", "North Indian Vegetarian"),
                    ("South Indian Vegetarian", "South Indian Vegetarian"),
                    ("Gujarati Vegetarian", "Gujarati Vegetarian"),
                    ("Jain Vegetarian", "Jain Vegetarian"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepreferences",
            name="include_driver",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepreferences",
            name="rent_period",
            field=models.CharField(
                choices=[
                    ("1-2 Days", "1-2 Days"),
                    (">3 Days", ">3 Days"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="vehicle_type_name",
            field=models.CharField(
                choices=[
                    ("Motorbike (1-2 people)", "Motorbike (1-2 people)"),
                    ("Bus (>30 people)", "Bus (>30 people)"),
                    ("MiniBus (20-30 people)", "MiniBus (20-30 people)"),
                    ("Van (12-15 people)", "Van (12-15 people)"),
                    ("Car (5-10 people)", "Car (5-10 people)"),
                    ("Luxury Car (5-8 people)", "Luxury Car (5-8 people)"),
                    ("Others", "Others"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendortype",
            name="name",
            field=models.CharField(
                choices=[
                    ("Vegetable Vendor", "Vegetable Vendor"),
                    ("Utensil Vendor", "Utensil Vendor"),
                    ("Travel Agent", "Travel Agent"),
                    ("Event Organizer", "Event Organizer"),
                    ("Other", "Other"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
